version: '3.8'

services:
  api:
    image: link-sharing-app-api9:latest
    depends_on:
      - db
    environment:
      - NODE_ENV=production
    ports:
      - target: 3000
        published: 3000
        mode: host
    env_file:
      - '.env'

  db:
    image: postgres:latest
    env_file:
      - '.env'
    volumes:
      - db:/var/lib/postgresql/data:z
    ports:
      - 5432:5432

volumes:
  db:
# networks:
#   default:
#     name: portfolio_network
#     external: true
