version: '3.8'

services:
  api:
    image: ghcr.io/fyargat/link-sharing-app-api:latest
    depends_on:
      - db
    environment:
      - NODE_ENV=production
    deploy:
      placement:
        constraints:
          - 'node.role=worker'
    ports:
      - target: 3000
        published: 3000
        mode: host
    env_file:
      - '.env'

  db:
    image: postgres:latest
    env_file:
      - '.env'
    volumes:
      - db:/var/lib/postgresql/data:z
    deploy:
      placement:
        constraints:
          - 'node.role=worker'
    ports:
      - target: 5432
        published: 5432
        mode: host

volumes:
  db:

networks:
  default:
    name: portfolio_network
    external: true
